spring.application.name=forevergym
spring.datasource.url=jdbc:mysql://localhost:3306/projectgym_local
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=83b1d9fd799440e703d48ce54874e7c1a34c9878cf0ba0aff37df8ccb834861c
jwt.expiration=86400000
